Sprint 3
stevenKirill/middle.messenger.praktikum.yandex pull request #3
Opened 2023-01-27 17:21 UTC by stevenKirill

2023-01-28 12:35 UTC, podlovchenko requested changes
Привет!

Круто, что:
- Используешь алиасы
- Типизированы методы API

Есть несколько замечаний:
- Ошибки типизации, попробуй выполнить команду `tsc --noEmit`
- Нет редиректа, если пользователь уже в системе
- Нет валидации данных на страницах авторизации и регистрации, по заданию должна быть по событиям focus/blur/submit, сейчас после первого события blur появляются ошибки, и почему-то исчезает введенное значение, это некорректное поведение системы
- Сервер на express отдает по / Hello world, а должен index.html
- Не отправляются сообщения в чате, не подгружается история сообщений, при попытке создать чат модальное окно стало некликабельным

2023-01-28 12:35 UTC, podlovchenko commented on package.json
> +    "test": "./node_modules/.bin/mocha"
Было бы отличное еще добавить команды запуска stylelint и проверки типов

2023-01-28 12:35 UTC, podlovchenko commented on src/api/chat/index.ts
> +      },
Можно внести внутрь HttpTransport

2023-01-28 12:35 UTC, podlovchenko commented on src/api/chat/types.ts
> +      phone: string;
В нескольких местах есть определение типа user, стоит вынести определение типа и переиспользовать

2023-01-28 12:35 UTC, podlovchenko commented on src/components/Avatar/avatar.css
> +  background-color: #ccc;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту, придерживаться одной цветовой палитры

2023-01-28 12:35 UTC, podlovchenko commented on src/components/BackLink/index.ts
> +import Block from 'core/block/Block';
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2023-01-28 12:35 UTC, podlovchenko commented on src/components/ChatItem/index.ts
> +  }
Если никаких преобразований пропсов нет, то можно короче
```suggestion
  constructor(props: ChatItemProps) {
    super(props);
  }
```
Вообще можно не определять конструктор, если он содержит только вызов родительского

2023-01-28 15:30 UTC, stevenKirill commented on src/components/ChatItem/index.ts
> +  }
ок

2023-01-28 15:31 UTC, stevenKirill commented on src/components/Avatar/avatar.css
> +  background-color: #ccc;
как я могу сохранять значения в полях формы регистрации ? если я делаю setProps у меня идет ререндер и я не знаю как сохранять поля в state

2023-01-28 15:32 UTC, stevenKirill commented on src/components/Avatar/avatar.css
> +  background-color: #ccc;
https://github.com/stevenKirill/middle.messenger.praktikum.yandex/blob/main/src/components/RegistrationForm/index.ts

2023-01-28 15:33 UTC, stevenKirill commented on src/components/Avatar/avatar.css
> +  background-color: #ccc;
если можешь помочь с рефакторингом было бы круто я уже второй спринт не знаю как лучше реализовать

2023-02-07 16:16 UTC, podlovchenko commented
Привет, спасибо за правки, работу принимаю)

2023-02-08 09:43 UTC, merged