Sprint 4
stevenKirill/middle.messenger.praktikum.yandex pull request #4
Opened 2023-02-18 11:16 UTC by stevenKirill

2023-02-19 14:11 UTC, maks88sgt requested changes
Привет! Отличная работа. У тебя получилось хорошее приложение с продуманной архитектурой и довольно чистым кодом. Практически все критерии спринта закрыты, но для того чтобы идти дальше нужно поправить следующие моменты:
1. Провести аудит зависимостей и избавиться от уязвимостей
2. Дополнить ридми списком использованных технологий и инструкциями по запуску тестов
3. Разобраться со сборкой докер-контейнера. Фактически у меня получилось это сделать не сразу. Первая проблема возникла с `webpack-dashboard` - сборка контейнера не завершалась больше 10 минут. Пофиксил использованием обычного вебпак, но возникла новая проблема - сборка падала из-за отсутствия scss лоадера. Возможно проблемы возникли из-за разных платформ, но с этим нужно разобраться и сделать так, чтобы все работало корректно во всех случаях.

2023-02-19 14:11 UTC, maks88sgt commented on package.json
> +    "stylelint": "^15.0.0",
Предлагаю использовать единый подход и везде использовать фиксированные версии зависимостей

2023-02-19 14:11 UTC, maks88sgt commented on src/components/ClipButton/clipButton.scss
> +  // background-image: url("../../assets/clip.png");
Закомментированный код лучше сразу удалять из проекта

2023-02-20 10:32 UTC, stevenKirill commented on package.json
> +    "stylelint": "^15.0.0",
ок

2023-02-20 10:32 UTC, stevenKirill commented on src/components/ClipButton/clipButton.scss
> +  // background-image: url("../../assets/clip.png");
ок

2023-02-20 10:34 UTC, stevenKirill commented
2. Дополнить ридми списком использованных технологий и инструкциями по запуску тестов - это уже есть

2023-02-20 10:44 UTC, stevenKirill commented
удалил webpacj dashboard , все собралось 
<img width="1404" alt="Screenshot 2023-02-20 at 13 42 34" src="https://user-images.githubusercontent.com/47239173/220083481-366e1f29-1543-419a-9e37-fc4b09670ef4.png">

2023-02-21 02:41 UTC, maks88sgt commented
Работу принял. Успехов на курсе!

2023-02-21 07:17 UTC, merged